image: picter/app-artists-ci

before_script:
  - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
  - npm install --quiet

stages:
  - review

review:
  stage: review
  script:
    - node src/index.js organisations/aperture > index.html
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: https://pages.staging.picter.io/$CI_BUILD_REF_NAME
  only:
    - branches
  except:
    - master
