image: noxan/docker-node-awscli-yarn

cache:
  key: 'pages'
  paths:
    - node_modules/

before_script:
  - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
  - yarn install --frozen-lockfile --pure-lockfile
  - npm rebuild node-sass

stages:
  - lint

lint:
  stage: lint
  script:
    - npm run lint
