image: noxan/docker-node-awscli-yarn

cache:
  key: 'app-curators'
  paths:
    - node_modules/

before_script:
  - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
  - yarn install --frozen-lockfile --pure-lockfile
  - npm rebuild node-sass

stages:
  - lint
  - deploy

lint:
  stage: lint
  script:
    - npm run lint

deploy-staging:
  stage: deploy
  script:
    - npm run build
    - aws s3 cp "./dist/" "s3://pages.staging.picter.io/" --acl public-read --recursive --region eu-west-1
  environment:
    name: Staging
    url: http://pages.staging.picter.io/
  only:
    - master
