image: kkarczmarczyk/node-yarn

before_script:
  - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
  - yarn

stages:
  - review

review:
  stage: review
  script:
    - node src/index.js organisations/aperture > index.html
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: https://$CI_BUILD_REF_NAME.$APPS_DOMAIN
  only:
    - branches
  except:
    - master
